# NumPy

In [2]:
# !pip install numpy

In [3]:
import numpy as np

In [4]:
## create Array using numpy

# create one d array

# import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2 = np.array([1,2,3,4,5])
print(arr2.reshape(1,5))    ## one row five columns

# print(arr2.reshape(1,4))

[[1 2 3 4 5]]


In [6]:
# two D array!
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
arr2.shape    ## two rows five columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [7]:
print(np.arange(0,10,2))
np.arange(0,10,2).reshape(5,1)     # five rows one column

[0 2 4 6 8]


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# identity matrix 

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
arr = np.array([[1,2,3],[4,5,6]])

print("array:",arr)
print("shape:",arr.shape)
print("number of dimensions:",arr.ndim)
print("size (number of elements):",arr.size)
print("Data type:",arr.dtype)
print("item size (in bytes):",arr.itemsize)

array: [[1 2 3]
 [4 5 6]]
shape: (2, 3)
number of dimensions: 2
size (number of elements): 6
Data type: int64
item size (in bytes): 8


In [11]:
## Numpy Vectorized Operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("addition:",arr1+arr2)

print("Substraction:",arr1-arr2)

print("Substraction:",arr1*arr2)

print("Substraction:",arr1/arr2)

addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Substraction: [ 10  40  90 160 250]
Substraction: [0.1 0.1 0.1 0.1 0.1]


In [12]:
# Universal Functions

arr = np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

# sine
print(np.sin(arr))

# Explore more Saqib!

# log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [13]:
## Array Slicig and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr[0]

array([1, 2, 3, 4])

In [16]:
print(arr[0][3])

4


In [17]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [18]:
print(arr[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
print(arr[0:2,2])

[3 7]


In [20]:
# modify array elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [21]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [23]:
### statistical concepts -- Normalization!
## To have a mean of 0 and standerd deviation of 1

data = np.array([1,2,3,4,5])

## calculate the mean and standered daviation

mean = np.mean(data)
std_dev = np.std(data)

## normalized the data 
normalize_data = (data-mean) / std_dev
print("Normalized data:", normalize_data)




Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [24]:
data =  np.array([1,2,3,4,5,6,7,8,9,10])

## mean
mean = np.mean(data)
print("mean:",mean)

## Median
median = np.median(data)
print("median:",median)

## Standered deviation
std_dev = np.std(data)
print("standerd deviation:",std_dev)

## Variance
variance = np.var(data)
print("variance:",variance)


mean: 5.5
median: 5.5
standerd deviation: 2.8722813232690143
variance: 8.25


In [33]:
## logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data>5  ## print true false! true if greater then 5
data[data>5] ## print Numbers!greater then 5

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])